from sastadev import iedims

result = iedims.getjeforms('maaggie')
print(result)
result = iedims.getjeforms('magie')
print(result)
result = iedims.getjeforms('vaassie')
print(result)
result = iedims.getjeforms('vasie')
print(result)
result = iedims.getjeforms('vaasie')
print(result)
result = iedims.getjeforms('magie')
print(result)
result = iedims.getjeforms('daggie')
print(result)
result = iedims.getjeforms('wijfie')
print(result)
result = iedims.getjeforms('wijffie')
print(result)
result = iedims.getjeforms('feessie')
print(result)
result = iedims.getjeforms('fesie')
print(result)
result = iedims.getjeforms('feesie')
print(result)
result = iedims.getjeforms('Keessie')
print(result)
result = iedims.getjeforms('Kesie')
print(result)
result = iedims.getjeforms('Keesie')
print(result)
result = iedims.getjeforms('fessie')
print(result)
result = iedims.getjeforms('kuchie')
print(result)
result = iedims.getjeforms('cluppie')
print(result)
result = iedims.getjeforms('rippie')
print(result)
result = iedims.getjeforms('Hupie')
print(result)
result = iedims.getjeforms('Huuppie')
print(result)
result = iedims.getjeforms('Huupie')
print(result)
result = iedims.getjeforms('Lissie')
print(result)
result = iedims.getjeforms('Jakoppie')
print(result)
result = iedims.getjeforms('trucie')
print(result)
