'''
Module to specify constant values that are used in the application
'''

# default locations of the data to train and test sastadev
actualanalysisfolder = 'actual'
analysiscomparisonfolder = 'analysiscomparison'
currentanalysisfolder = 'current'
corrfolder = 'corr'
nocorrfolder = 'nocorr'
previousanalysisfolder = 'previous'
analysesfolder = 'analyses'
bronzefolder = 'bronze'
confidencefolder = 'confidence'
correctionref_folder = 'correctionref'
figuresfolder = '_Figures'
formsfolder = 'forms'
indatafolder = 'indata'
intreebanksfolder = 'intreebanks'
loggingfolder = 'logging'
outtreebanksfolder = 'outtreebanks'
resultsfolder = 'results'
silverfolder = 'silver'
silverpermfolder = 'silverperm'
testsetsfolder = 'testsets'
dataset_treebanksfolder = 'dataset_treebanksfolder'
errorsummaryfolder = 'errorsummaries'
lemmafolder = 'lemmas'

analysissuffix = '_analysis'
analysistsvsuffix = '_analysis.tsv'
bronzesuffix = '_bronze'
byuttscoressuffix = '_scoresbyutt'
silversuffix = '_silver'
correctionrefsuffix = '_correctionref'
permprefix = 'perm_'
checksuffix = '_platinum.check.tsv'
checkeditedsuffix = '_platinum.check-edited.tsv'
platinumsuffix = '.platinum.tsv'
platinumeditedsuffix = '.platinum-edited.tsv'

errorsummarysuffix = '_errorsummary'
errorloggingsuffix = '_errorlogging'