'''
Module to specify constant values that are used in the application
'''

# default locations of the data to train and test sastadev
actualfolder = 'actual'
actualanalysisfolder = actualfolder
actual_sasfolder = actualfolder
analysiscomparisonfolder = 'analysiscomparison'
currentfolder = 'current'
currentanalysisfolder = currentfolder
current_sasfolder = currentfolder
corrfolder = 'corr'
nocorrfolder = 'nocorr'
gramerr_suffix = '_analysis_gramerr'
gramerr_tsv_suffix = '_analysis_gramerr.tsv'
overallsasfolder = '_SAS_overall'
previousanalysisfolder = 'previous'
previous_sasfolder = 'previous'
analysesfolder = 'analyses'
bronzefolder = 'bronze'
confbyuttfolder = 'conf_by_utt'
confidencefolder = 'confidence'
correctionref_folder = 'correctionref'
datafolder  = 'data'
distancesheetname = 'Distance'
f1byuttidsheetname = 'F1byUttId'
figuresfolder = '_Figures'
formsfolder = 'forms'
indatafolder = 'indata'
intreebanksfolder = 'intreebanks'
loggingfolder = 'logging'
metasheetname = 'Meta'
outtreebanksfolder = 'outtreebanks'
overallsasfolder = '_SAS_overall'
persistent_sas_folder = 'persistent'
persistent_comments_filename = 'persistent_sas_mismatch_comments.xlsx'
persistentfolder = 'persistent'
resultsfolder = 'results'
sas_analyses_folder = 'sas_analyses'
sasanalysissuffix = '_sasanalysis'
sasanalysistsvsuffix = '_sasanalysis.tsv'
sasfolder = 'SAS'
sasimpact_sheetname = 'SAS_impact'
sas_mismatches_filename = 'sas_mismatches.xlsx'
sas_suffix = '_sas'
sas_summarysuffix = '_SASsummary'
scores_by_qid_folder = 'qidscores'
scorefrqsheetname = 'ScoreFrq'
sentencessheetname = 'Sentences'
silverfolder = 'silver'
silverpermfolder = 'silverperm'
summarysheetname = 'Summary'
testsetsfolder = 'testsets'
treesfolder = 'trees'
utt_order_comparison_folder = 'utt_order_comparison'
uttinimpactsheetname = 'UttinImpact'
uttnotinimpactsheetname = 'UttNotinImpact'
uttsfoundsheetname = 'UttsFound'
dataset_treebanksfolder = 'dataset_treebanksfolder'
errorsummaryfolder = 'errorsummaries'
lemmafolder = 'lemmas'

analysissuffix = '_analysis'
sasanalysissuffix = '_sasanalysis'
analysistsvsuffix = '_analysis.tsv'
bronzesuffix = '_bronze'
byuttscoressuffix = '_scoresbyutt'
correctedsuffix = '_corrected'
silversuffix = '_silver'
correctionrefsuffix = '_correctionref'
permprefix = 'perm_'
checksuffix = '_platinum.check.tsv'
checkeditedsuffix = '_platinum.check-edited.tsv'
platinumsuffix = '.platinum.tsv'
platinumeditedsuffix = '.platinum-edited.tsv'

errorsummarysuffix = '_errorsummary'
errorloggingsuffix = '_errorlogging'

analysis_mode = 0
sas_mode = 1
gramerr_mode = 2